[package]
name = "nft-shares"
version = "0.0.2"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dev-dependencies]
near-sdk = { path = "../../near-sdk" }
near-sdk-sim = { path = "../../near-sdk-sim" }

# remember to include a line for each contract
shares = { path = "./ft" }

[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true

[workspace]
# remember to include a member for each contract
members = [
  "ft"
]

[[example]]
name = "heavy"

